---
# =============================
# Auth Service Deployment
# =============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: auth-service
          image: ghcr.io/abdelrahman/auth-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: APP_KEY
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: DB_PASSWORD

---
# =============================
# Auth Service ClusterIP
# =============================
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

---
# =============================
# Product Service Deployment
# =============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: product-service
          image: ghcr.io/abdelrahman/product-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: product-service-secrets
                  key: APP_KEY
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: product-service-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: product-service-secrets
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: product-service-secrets
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: product-service-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-service-secrets
                  key: DB_PASSWORD

---
# =============================
# Product Service ClusterIP
# =============================
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: product
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

---
# =============================
# Ingress
# =============================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-micro-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: auth.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80
    - host: product.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 80
